# https://github.com/actions/labeler

name: PR Labels
on:
- workflow_run:
    workflows: ["Review PR"]
    types:
      - completed

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - name: Add labels
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/config/labeler.yml
