# https://github.com/actions/labeler

name: PR Labels
on:
  workflow_run:
    workflows: ["Review PR"]
    types:
      - completed

jobs:
  apply:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Add labels
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/config/labeler.yml
